### ISSUE TITLE
Discovery api results are inconsistent across api versions

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/multicluster-controlplane#128]
It seems that Kubernetes has a new Aggregated Discovery api:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3352-aggregated-discovery

The issue is that for mc-cp the response is not same between the legacy and new aggregated mode. This causes problem where the addon framework thinks the CSR api type is not available. 
https://github.com/open-cluster-management-io/addon-framework/blob/44852ea0722f413257fe49016009aaba25abbb42/pkg/utils/csr_helpers.go#L198

**Legacy Response:**

```yaml
kind: APIGroupList
apiVersion: v1
groups:
- name: apiregistration.k8s.io
  versions:
  - groupVersion: apiregistration.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: apiregistration.k8s.io/v1
    version: v1
- name: events.k8s.io
  versions:
  - groupVersion: events.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: events.k8s.io/v1
    version: v1
- name: authentication.k8s.io
  versions:
  - groupVersion: authentication.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: authentication.k8s.io/v1
    version: v1
- name: authorization.k8s.io
  versions:
  - groupVersion: authorization.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: authorization.k8s.io/v1
    version: v1
- name: certificates.k8s.io
  versions:
  - groupVersion: certificates.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: certificates.k8s.io/v1
    version: v1
- name: rbac.authorization.k8s.io
  versions:
  - groupVersion: rbac.authorization.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: rbac.authorization.k8s.io/v1
    version: v1
- name: admissionregistration.k8s.io
  versions:
  - groupVersion: admissionregistration.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: admissionregistration.k8s.io/v1
    version: v1
- name: apiextensions.k8s.io
  versions:
  - groupVersion: apiextensions.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: apiextensions.k8s.io/v1
    version: v1
- name: coordination.k8s.io
  versions:
  - groupVersion: coordination.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: coordination.k8s.io/v1
    version: v1
- name: discovery.k8s.io
  versions:
  - groupVersion: discovery.k8s.io/v1
    version: v1
  preferredVersion:
    groupVersion: discovery.k8s.io/v1
    version: v1
- name: flowcontrol.apiserver.k8s.io
  versions:
  - groupVersion: flowcontrol.apiserver.k8s.io/v1beta2
    version: v1beta2
  preferredVersion:
    groupVersion: flowcontrol.apiserver.k8s.io/v1beta2
    version: v1beta2
- name: cluster.open-cluster-management.io
  versions:
  - groupVersion: cluster.open-cluster-management.io/v1
    version: v1
  - groupVersion: cluster.open-cluster-management.io/v1beta2
    version: v1beta2
  - groupVersion: cluster.open-cluster-management.io/v1beta1
    version: v1beta1
  - groupVersion: cluster.open-cluster-management.io/v1alpha1
    version: v1alpha1
  preferredVersion:
    groupVersion: cluster.open-cluster-management.io/v1
    version: v1
- name: work.open-cluster-management.io
  versions:
  - groupVersion: work.open-cluster-management.io/v1
    version: v1
  - groupVersion: work.open-cluster-management.io/v1alpha1
    version: v1alpha1
  preferredVersion:
    groupVersion: work.open-cluster-management.io/v1
    version: v1
- name: addon.open-cluster-management.io
  versions:
  - groupVersion: addon.open-cluster-management.io/v1alpha1
    version: v1alpha1
  preferredVersion:
    groupVersion: addon.open-cluster-management.io/v1alpha1
    version: v1alpha1
- name: authentication.open-cluster-management.io
  versions:
  - groupVersion: authentication.open-cluster-management.io/v1beta1
    version: v1beta1
  - groupVersion: authentication.open-cluster-management.io/v1alpha1
    version: v1alpha1
  preferredVersion:
    groupVersion: authentication.open-cluster-management.io/v1beta1
    version: v1beta1
```

**Aggregated Response:**

```
kind: APIGroupDiscoveryList
apiVersion: apidiscovery.k8s.io/v2beta1
metadata: {}
items:
- metadata:
    name: apiregistration.k8s.io
    creationTimestamp:
  versions:
  - version: v1
    resources:
    - resource: apiservices
      responseKind:
        group: ''
        version: ''
        kind: APIService
      scope: Cluster
      singularResource: apiservice
      verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
      categories:
      - api-extensions
      subresources:
      - subresource: status
        responseKind:
          group: ''
          version: ''
          kind: APIService
        verbs:
        - get
        - patch
        - update
    freshness: Current
```

Using the `nativeClient.Discovery().WithLegacy()` forces the addon-framework to use the legacy response format. I thought https://github.com/open-cluster-management-io/multicluster-controlplane/pull/127 will address the issue. But it does not. I am sure how to update mc-cp to correctly return the discovery reponse.
